server:
  port: 9090


spring:
  drone:
    scheduling:
      drone-status: '0 0/5 * * * ?'
  h2:
    console:
      enabled: true
      path: /h2-console
    jpa:
      show-sql: true

core:
  service:
    db:
      password:
      username: sa
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testing;MODE=PostgreSQL;DB_CLOSE_DELAY=-1